services:
  - type: web
    name: diana-beach-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: diana_beach
      - key: JWT_SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
